# Generated by Django 3.0.2 on 2020-05-07 13:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 5, 7, 13, 21, 9, 626195, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
