# Generated by Django 3.0.6 on 2020-10-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201016_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('access_dashboard', 'Access Dashboard'),)},
        ),
    ]
